backend:
  image: crud-backend
  ports:
    - "5000:5000"
  environment:
    DB_USER: admin
    DB_PASS: Cloud123
    DB_HOST: database-1.cdkmgk6kaqjz.us-west-2.rds.amazonaws.com
    DB_NAME: cruddb

frontend:
  image: crud-nginx
  ports:
    - "80:80"
  depends_on:
    - backend
